Repository wrappid/guide-module, pull requests merged in 2024-09, with the labels that each got.

#281 docs(global): :memo: update CoreSkeleton documentation
  app/components/component-docs/feedback/CoreSkeleton.docs.js
Labels: documentation, enhancement

#268 docs(global): 📝 update CoreLinearProgress documentation
  app/components/component-docs/feedback/CoreLinearProgress.docs.js
Labels: documentation, enhancement

#280 docs(global): :memo: update documentation CoreDatepicker
  app/components/component-docs/inputs/CoreDateRangepicker.docs.js
  app/components/component-docs/inputs/CoreDatepicker.docs.js
Labels: documentation

#283 docs(global): :memo: update documentation CoreDateRangepicker, CoreDateTimePicker
  app/components/component-docs/inputs/CoreDateTimePicker.docs.js
  app/components/component-docs/inputs/CoreDateTimeRangePicker.docs.js
  app/components/component-docs/inputs/CoreMultiTimeRangePicker.docs.js
  app/components/component-docs/inputs/CoreTimePicker.docs.js
  app/components/component-docs/inputs/CoreTimeRangePicker.docs.js
Labels: documentation

#285 docs(global): :memo: update documentation CoreFab
  app/components/component-docs/inputs/CoreFab.docs.js
Labels: documentation

#287 docs(global): :memo: updateCoreSwitch documentation
  app/components/component-docs/inputs/CoreSwitch.docs.js
Labels: documentation

#288 docs(global): 📝 update CoreSnackbar documentation
  app/components/component-docs/feedback/CoreSnackbar.docs.js
Labels: documentation

#290 fix(global): :adhesive_bandage: removed position:sticky from Components.js
  app/components/component-docs/Components.js
Labels: bugfix

#293 docs(core): :memo: update CoreSelect documentation
  app/components/component-docs/inputs/CoreSelect.docs.js
Labels: documentation

#295 docs(global): :memo: update CoreRating documentation
  app/components/component-docs/inputs/CoreRating.docs.js
Labels: documentation

#298 enhancement: auto basic code sample creation
  app/components/component-docs/ComponentDocs.js
  app/components/component-docs/dataDisplay/CoreAvatar.docs.js
  app/components/component-docs/inputs/CoreTextField.docs.js
Labels: enhancement, frontend, p1, bugfix

#300 feat(core): :art: inpus/CorePhone update structure
  app/components/component-docs/inputs/CorePhone.docs.js
Labels: enhancement

#301 docs(global): :memo: update CoreAutocomplete documentation
  app/components/component-docs/inputs/CoreAutocomplete.docs.js
Labels: documentation

#303 docs(global): :memo: docs update CoreAccordian
  app/components/component-docs/surfaces/CoreAccordion.docs.js
Labels: documentation

#306 docs(core): :memo: update documentation of CoreCard
  app/components/component-docs/surfaces/CoreCard.docs.js
  app/components/component-docs/surfaces/CoreCardActionArea.docs.js
  app/components/component-docs/surfaces/CoreCardActions.docs.js
  app/components/component-docs/surfaces/CoreCardContent.docs.js
Labels: documentation, enhancement

#307 docs(core): :memo: docs update CoreTab
  app/components/component-docs/navigation/CoreTab.docs.js
Labels: documentation

#311 fix(global): :bug: fix basicSample in AutoComplete
  app/components/component-docs/inputs/CoreAutocomplete.docs.js
Labels: bugfix

#316 docs(core): navigation/CoreLink structure
  app/components/component-docs/ComponentDocs.js
  app/components/component-docs/navigation/CoreLink.docs.js
Labels: bugfix

#317 docs(global): :memo: CoreGrid docomentation has been updated
  app/components/component-docs/layouts/CoreGrid.docs.js
Labels: documentation, enhancement

#318 docs(global): :memo: update CoreStack docs
  app/components/component-docs/layouts/CoreStack.docs.js
Labels: documentation

#319 docs(global): :memo: update docs CoreAvatar and CoreAvatarGroup
  app/components/component-docs/dataDisplay/CoreAvatar.docs.js
  app/components/component-docs/dataDisplay/CoreAvatarGroup.docs.js
Labels: documentation

#321 docs(global): :memo: update documentation of CorePaper
  app/components/component-docs/surfaces/CorePaper.docs.js
Labels: documentation

#327 docs(global): :memo: update docs CoreAccordionDetail,CoreAccordionSum…
  app/components/component-docs/surfaces/CoreAccordionDetail.docs.js
  app/components/component-docs/surfaces/CoreAccordionSummary.docs.js
Labels: documentation

#337 docs(global): :memo: dataDisplay/CoreEmailLink , CorePhoneLink
  app/components/CodeImport.js
  app/components/component-docs/DocsRegistry.js
  app/components/component-docs/dataDisplay/CoreEmailLink.docs.js
  app/components/component-docs/dataDisplay/CoreEmailOrPhoneLink.docs.js
  app/components/component-docs/dataDisplay/CorePhoneLink.docs.js
Labels: bugfix

#329 docs(global): :memo: corespan documentation has been updated
  app/components/component-docs/layouts/CoreSpan.docs.js
Labels: documentation, enhancement

#330 fix(global): :bug: fix basicSample not working CoreSelect
  app/components/component-docs/inputs/CoreSelect.docs.js
Labels: bugfix

#332 docs(core): :memo: corefilepicker has documentation has been updated
  app/components/component-docs/inputs/CoreFilePicker.docs.js
Labels: documentation

#335 docs(global): :memo: update docs for CoreCollapse
  app/components/component-docs/surfaces/CoreCollapse.docs.js
Labels: documentation

#339 docs(global): :memo: coreimagepicker documentation updated
  app/components/component-docs/inputs/CoreImagePicker.docs.js
Labels: documentation, enhancement

#341 docs(global): 📝 dataDisplay/CoreTable related documentations
  app/components/component-docs/dataDisplay/CoreTable.docs.js
  app/components/component-docs/dataDisplay/CoreTableBody.docs.js
  app/components/component-docs/dataDisplay/CoreTableBodyCell.docs.js
  app/components/component-docs/dataDisplay/CoreTableCell.docs.js
  app/components/component-docs/dataDisplay/CoreTableContainer.docs.js
  app/components/component-docs/dataDisplay/CoreTableFooter.docs.js
  app/components/component-docs/dataDisplay/CoreTableHead.docs.js
  app/components/component-docs/dataDisplay/CoreTableHeadCell.docs.js
  app/components/component-docs/dataDisplay/CoreTableHeadRow.docs.js
  app/components/component-docs/dataDisplay/CoreTablePagination.docs.js
  app/components/component-docs/dataDisplay/CoreTableRow.docs.js
  app/components/component-docs/dataDisplay/CoreTableSortLabel.docs.js
  app/components/component-docs/dataDisplay/CoreTimer.docs.js
Labels: documentation, bugfix
