Repository wrappid/guide-module, pull requests merged in 2024-01, with the labels that each got.

#47 docs: :memo: Text documentation related changes
  app/components/styles-docs/StyleUtilitiesSamples.js
Labels: documentation

#82 bg color and linting
  app/components/CodeBlock.js
  app/components/styles-docs/StyleUtilities.js
  app/components/styles-docs/StyleUtilitiesSamples.js
  package.json
Labels: documentation, cleanup

#49 docs: :memo: Add a scroll in Component Menu section
  .eslint/app/.eslintrc.js
  .eslint/service/.eslintrc.js
  .eslintrc.js
  .github/workflows/pr-guardrails.yml
  LICENSE
  app/components/component-docs/ComponentsMenu.js
  app/components/component-docs/navigation/CoreMenu.docs.js
  lint-staged.config.js
  package-lock.json
  package.json
  service/functions/test.functions.js
Labels: documentation

#83 fix(core): :bug: border radius issue and color related updates
  app/components/styles-docs/StyleUtilities.js
  app/components/styles-docs/StyleUtilitiesSamples.js
Labels: bug, documentation

#87 Merge development into main
  .eslint/app/.eslintrc.js
  .eslint/service/.eslintrc.js
  .eslintrc.js
  .github/workflows/pr-guardrails.yml
  LICENSE
  app/components/component-docs/ComponentsMenu.js
  app/components/component-docs/navigation/CoreMenu.docs.js
  app/components/styles-docs/StyleUtilities.js
  app/components/styles-docs/StyleUtilitiesSamples.js
  lint-staged.config.js
  package-lock.json
  package.json
  service/functions/test.functions.js
Labels: enhancement

#86 bug: import fix
  .github/workflows/pr-guardrails.yml
  service/validations.registry.js
Labels: bug

#90 fix(core): :bug: overflow-x & overflow-y problem resolved
  app/components/styles-docs/StyleUtilitiesSamples.js
Labels: enhancement

#88 StyleUtilitySamples Interaction related changes
  app/components/styles-docs/StyleUtilitiesSamples.js
Labels: documentation, enhancement

#92 Merge development into main
  .github/workflows/pr-guardrails.yml
  app/components/styles-docs/StyleUtilitiesSamples.js
  service/validations.registry.js
Labels: enhancement
