Repository wrappid/guide-module, pull requests merged in 2024-08, with the labels that each got.

#162 fix: :bug: There was a overlapping that was happening in valid props section in CoreComponent documentation
  app/components/ComponentProps.js
Labels: bug fix

#168 fix: :bug: CodeBlock text highlight not working
  app/components/CodeBlock.js
Labels: bugfix

#164 docs: :memo: The completion of improvement of documentation of CoreList
  app/components/component-docs/dataDisplay/CoreList.docs.js
Labels: enhancement

#177 docs: modify documentation for CoreChip
  app/components/component-docs/dataDisplay/CoreChip.docs.js
Labels: documentation

#173 feat(global): :bug: documentation for CoreBadge
  app/components/component-docs/dataDisplay/CoreBadge.docs.js
Labels: documentation

#180 enhancement: documentation for CoreH1,H2,H3,H4,H5,H6
  app/components/component-docs/dataDisplay/CoreH1.docs.js
  app/components/component-docs/dataDisplay/CoreH2.docs.js
  app/components/component-docs/dataDisplay/CoreH3.docs.js
  app/components/component-docs/dataDisplay/CoreH4.docs.js
  app/components/component-docs/dataDisplay/CoreH5.docs.js
  app/components/component-docs/dataDisplay/CoreH6.docs.js
Labels: documentation

#181 bugfix: coreicon icon props was not given properly in CoreList
  app/components/component-docs/dataDisplay/CoreList.docs.js
Labels: bugfix

#184 fix(core): :bug: error showing in CoreListItem
  app/components/component-docs/dataDisplay/CoreListItem.docs.js
Labels: documentation, bugfix

#185 docs(core): :memo: add typography documentation
  app/components/component-docs/dataDisplay/CoreTypographyBody1.docs.js
  app/components/component-docs/dataDisplay/CoreTypographyBody2.docs.js
  app/components/component-docs/dataDisplay/CoreTypographyButton.docs.js
  app/components/component-docs/dataDisplay/CoreTypographyCaption.docs.js
  app/components/component-docs/dataDisplay/CoreTypographyOverline.docs.js
  app/components/component-docs/dataDisplay/CoreTypographySubtitle1.docs.js
  app/components/component-docs/dataDisplay/CoreTypographySubtitle2.docs.js
Labels: documentation

#187 docs(core): :memo: add CodeImport component in CoreTypography*
  app/components/component-docs/dataDisplay/CoreTypographyBody1.docs.js
  app/components/component-docs/dataDisplay/CoreTypographyBody2.docs.js
  app/components/component-docs/dataDisplay/CoreTypographyButton.docs.js
  app/components/component-docs/dataDisplay/CoreTypographyCaption.docs.js
  app/components/component-docs/dataDisplay/CoreTypographyOverline.docs.js
  app/components/component-docs/dataDisplay/CoreTypographySubtitle1.docs.js
  app/components/component-docs/dataDisplay/CoreTypographySubtitle2.docs.js
Labels: documentation

#188 fix(core): :bug: codesample of CoreImage correction
  app/components/component-docs/dataDisplay/CoreImage.docs.js
Labels: bugfix

#175 docs(global): :memo: modify documentation for CoreDivider
  app/components/component-docs/dataDisplay/CoreDivider.docs.js
Labels: documentation

#192 fix(core): :bug: corelistitembutton has been fixed and corelistitem document has been corrected
  app/components/component-docs/dataDisplay/CoreListItem.docs.js
  app/components/component-docs/dataDisplay/CoreListItemButton.docs.js
Labels: documentation, bugfix

#197 fix(core): :bug: CoreItemListText documentation has been updated and the props is visible now
  app/components/component-docs/dataDisplay/CoreListItemText.docs.js
Labels: bugfix

#203 fix(core): :bug: corelistitemsecondaryaction has been implemented
  app/components/component-docs/dataDisplay/CoreListItemSecondaryAction.docs.js
Labels: bugfix

#194 docs(core): :memo: update docomentation of CoreListItemIcon
  app/components/component-docs/dataDisplay/CoreListItemIcon.docs.js
Labels: documentation

#204 docs(global): :memo: fix CoreBackDrop documentation
  app/components/component-docs/feedback/CoreBackdrop.docs.js
Labels: documentation

#190 fix(core): :bug: the docomentation is not present has been updated
  app/components/component-docs/dataDisplay/CoreListItemAvatar.docs.js
Labels: documentation, bugfix

#199 docs(global): :memo: update documentation for CoreAlert
  app/components/component-docs/feedback/CoreAlert.docs.js
Labels: documentation

#195 enhancement: CoreTooltip Documentation
  app/components/component-docs/dataDisplay/CoreTooltip.docs.js
Labels: documentation

#171 bug: fix documentation for CoreAvatar
  app/components/component-docs/dataDisplay/CoreAvatar.docs.js
Labels: documentation

#209 docs(core): :memo: add CoreLabel documentation
  app/components/component-docs/dataDisplay/CoreLabel.docs.js
Labels: documentation, bugfix

#208 docs(core): 📝CoreListSubheader documentation has been updated
  app/components/component-docs/dataDisplay/CoreListSubheader.docs.js
Labels: documentation

#206 docs: CoreCircularProgress documentation
  app/components/component-docs/feedback/CoreCircularProgress.docs.js
Labels: documentation

#213 feat(core): :art: new component added
  README.md
  app/components/component-docs/ComponentDocs.js
  app/components/component-docs/dataDisplay/CoreAvatar.docs.js
Labels: enhancement

#214 feat(core): :zap: added expanded code section with copy to clipboard feature
  app/components/CodeSample.js
  app/components/component-docs/dataDisplay/CoreAvatar.docs.js
Labels: enhancement

#219 feat(core): :art: update CoreImage docs structure
  app/components/component-docs/dataDisplay/CoreImage.docs.js
Labels: documentation, enhancement

#221 docs(global): :memo: update CoreTooltip documentation
  app/components/component-docs/dataDisplay/CoreTooltip.docs.js
Labels: documentation

#222 docs(global): 📝 update documentation
  app/components/component-docs/feedback/CoreDialog.docs.js
Labels: documentation

#220 docs(global): :art: CoreLabel documentation structure update
  app/components/component-docs/dataDisplay/CoreLabel.docs.js
Labels: documentation, bugfix

#217 enhancement : update documentation for CoreBadge
  app/components/component-docs/dataDisplay/CoreBadge.docs.js
Labels: documentation

#223 docs(global): :memo: corelistitem docomentation has been updated successfully
  app/components/component-docs/dataDisplay/CoreListItem.docs.js
Labels: documentation, enhancement

#224 docs(global): :memo: corelistitemavatar documentation has been updated successfully
  app/components/component-docs/dataDisplay/CoreListItemAvatar.docs.js
Labels: documentation, enhancement

#225 docs(global): :memo: modify documentation for CoreH1,H2,H3,H4,H5,H6
  app/components/component-docs/dataDisplay/CoreH.docs.js
  app/components/component-docs/dataDisplay/CoreH1.docs.js
  app/components/component-docs/dataDisplay/CoreH2.docs.js
  app/components/component-docs/dataDisplay/CoreH3.docs.js
  app/components/component-docs/dataDisplay/CoreH4.docs.js
  app/components/component-docs/dataDisplay/CoreH5.docs.js
  app/components/component-docs/dataDisplay/CoreH6.docs.js
Labels: documentation

#227 docs(global): :memo: corelistitembutton is documentation
  app/components/component-docs/dataDisplay/CoreListItemButton.docs.js
Labels: documentation

#229 docs(global): :memo: update documentation for CoreAlert
  app/components/component-docs/feedback/CoreAlert.docs.js
Labels: documentation

#230 docs(global): 📝 corelistitemicon is documentation
  app/components/component-docs/dataDisplay/CoreListItemIcon.docs.js
Labels: documentation, enhancement

#232 docs(global): :memo: update documentation of CoreLinearProgress
  app/components/component-docs/feedback/CoreLinearProgress.docs.js
Labels: documentation

#233 docs(global): 📝 corelistitemicon is documentation has been updated
  app/components/component-docs/dataDisplay/CoreListItemIcon.docs.js
Labels: documentation

#234 docs(global): :memo: update documentation for BackDrop
  app/components/component-docs/feedback/CoreBackdrop.docs.js
Labels: documentation

#236 docs(global): 📝 corelistitembutton is documentation layout removed
  app/components/component-docs/dataDisplay/CoreListItemAvatar.docs.js
Labels: documentation

#238 docs(core): :memo: corelistitem layout has been removed
  app/components/component-docs/dataDisplay/CoreListItem.docs.js
Labels: documentation

#237 docs(core): :memo: update documentation for CoreCircularProgress
  app/components/component-docs/feedback/CoreCircularProgress.docs.js
Labels: documentation

#240 docs(global): :memo: component StatusText dynamic documentation added
  app/components/component-docs/dataDisplay/StatusText.docs.js
Labels: documentation

#242 docs(global): :memo: corelistitem secondaryaction document has updated successfully
  app/components/component-docs/dataDisplay/CoreListItemSecondaryAction.docs.js
Labels: documentation

#246 docs(global): :memo: dataDisplay/CoreTimer add documentation
  app/components/component-docs/dataDisplay/CoreTimer.docs.js
Labels: documentation

#248 docs(global): :memo: inputs/CoreInput custom onChange example
  app/components/component-docs/inputs/CoreInput.docs.js
Labels: documentation, bugfix

#249 docs(global): :memo: update documentation
  app/components/component-docs/feedback/CoreSkeleton.docs.js
Labels: documentation, enhancement

#250 docs(core): :memo: update CoreCheckbox documentation
  app/components/component-docs/inputs/CoreCheckbox.docs.js
Labels: documentation

#251 fix(global): :ambulance: hotfix remove external library import
  app/components/component-docs/feedback/CoreDialog.docs.js
Labels: hotfix

#253 docs: update documentation for CoreButton
  app/components/component-docs/inputs/CoreButton.docs.js
Labels: documentation

#256 fix(global): :bug: dataDisplay/CoreChip clickable link
  app/components/component-docs/dataDisplay/CoreChip.docs.js
Labels: bugfix

#261 docs(core): :memo: documentation update for CoreAlertTitle
  app/components/component-docs/feedback/CoreAlertTitle.docs.js
Labels: documentation

#262 docs(global): :memo: corelist documentaion has updated
  app/components/component-docs/dataDisplay/CoreList.docs.js
Labels: documentation, enhancement

#263 fix(global): :bug: corelistitemtext docs updated new format
  app/components/component-docs/dataDisplay/CoreListItemText.docs.js
Labels: documentation, enhancement, bugfix

#264 docs(global): :memo: corelistsubheader documentaion has been updated
  app/components/component-docs/dataDisplay/CoreListSubheader.docs.js
Labels: documentation, enhancement

#265 docs(global): :memo: fix documentation CoreDivider
  app/components/component-docs/dataDisplay/CoreDivider.docs.js
Labels: documentation

#267 docs(global): :memo: update documentation CoreCircularProgress
  app/components/component-docs/feedback/CoreCircularProgress.docs.js
Labels: documentation

#273 docs(global): :memo: corebox documentation has been updated
  app/components/component-docs/layouts/CoreBox.docs.js
Labels: documentation, enhancement

#257 feat(global): :art: dataDisplay/CoreImage add border at place of image
  app/components/component-docs/dataDisplay/CoreImage.docs.js
Labels: documentation

#258 docs(global): :memo: update documentation CoreAlert
  app/components/component-docs/feedback/CoreAlert.docs.js
Labels: documentation

#274 fix(global): :memo: update documentation for CoreBadge
  app/components/component-docs/dataDisplay/CoreBadge.docs.js
Labels: documentation

#277 docs(global): :memo: corecontainer documentation fixed
  app/components/component-docs/layouts/CoreContainer.docs.js
Labels: documentation, enhancement, bugfix
