Repository wrappid/guide-module, pull requests merged in 2024-02, with the labels that each got.

#94 feat(core): :sparkles: linear-gradient styles documentation added
  app/components/styles-docs/StyleUtilities.js
  app/components/styles-docs/StyleUtilitiesSamples.js
Labels: documentation

#101 fix(global): :fire: correct the typo
  app/styles/DefaultModuleStyles.js
  app/styles/LargeModuleStyles.js
  app/styles/MediumModuleStyles.js
  app/styles/SmallModuleStyles.js
  app/styles/XLargeModuleStyles.js
  app/styles/XXLargeModuleStyles.js
Labels: bug

#103 refactor: merge from template development
  .eslintrc.js
  .github/scripts/attribution_header_adder.sh
  .github/workflows/auto-create-and-merge-pr.yml
  .gitignore
  .husky/pre-commit
  app/styles/DefaultModuleStyles.js
  app/styles/LargeModuleStyles.js
  app/styles/MediumModuleStyles.js
  app/styles/SmallModuleStyles.js
  app/styles/XLargeModuleStyles.js
  app/styles/XXLargeModuleStyles.js
  package-lock.json
  package.json
  service/controllers.registry.js
  service/controllers.registry.ts
  service/controllers/test.controller.ts
  service/functions.registry.js
  service/functions.registry.ts
  service/functions/test.functions.js
  service/functions/test.functions.ts
  service/middlewares.registry.js
  service/middlewares.registry.ts
  service/middlewares/test.middleware.ts
  service/models.registry.js
  service/models.registry.ts
  service/models/TestDatas.model.js
  service/models/TestDatas.model.ts
  service/routes.registry.ts
  service/tasks.registry.js
  service/tasks.registry.ts
  service/tasks/TestTask.js
  service/tasks/TestTask.ts
  service/validations.registry.js
  service/validations.registry.ts
  service/validations/test.validation.ts
Labels: enhancement

#97 styling: basic ui patches
  .vscode/settings.json
  app/components/component-docs/dataDisplay/CoreAvatar.docs.js
  app/components/component-docs/dataDisplay/CoreAvatarGroup.docs.js
  app/components/component-docs/dataDisplay/CoreBadge.docs.js
  app/components/styles-docs/StyleUtilities.js
  app/components/styles-docs/StyleUtilitiesSamples.js
Labels: documentation

#106 sample code overlapping problem resolved
  app/components/CodeBlock.js
Labels: bug

#107 merge: from Development
  .eslint/service/.eslintrc.js
  .eslintrc.js
  .vscode/settings.json
  app/components/CodeBlock.js
  app/components/component-docs/dataDisplay/CoreAvatar.docs.js
  app/components/component-docs/dataDisplay/CoreAvatarGroup.docs.js
  app/components/component-docs/dataDisplay/CoreBadge.docs.js
  app/components/styles-docs/StyleUtilities.js
  app/components/styles-docs/StyleUtilitiesSamples.js
  package-lock.json
  package.json
  service/controllers/test.controller.ts
  service/functions/test.functions.ts
  service/middlewares/test.middleware.ts
  service/tasks/TestTask.ts
  service/validations/test.validation.ts
Labels: bug, cleanup
