Repository wrappid/guide-module, pull requests merged in 2024-04, with the labels that each got.

#135 fix(global): :bug: key prop added to layoutViewer and styles layout removed
  app/components/layout-docs/LayoutViewer.js
  app/routes.registry.js
Labels: bug

#136 documentation: line-height and word-spacing documentation added
  app/components/styles-docs/Styles.js
  app/components/styles-docs/StylesSamples.js
Labels: documentation

#137 docs(core): :memo: gradient aspect ratio set to 1:1, Cursor note added
  app/components/styles-docs/StylesSamples.js
Labels: documentation

#138 refactor(core): :recycle: add scrolling in CoreToc, CoreMenu and comp…
  app/components/component-docs/Components.js
Labels: enhancement

#142 fix(global): :bug: tramsform rotate documentation related changes
  app/components/styles-docs/StylesSamples.js
Labels: bug

#144 CoreForm sample documentation
  app/components/component-docs/inputs/forms/CoreForm.docs.js
Labels: enhancement
